services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:10
    environment:
      - API_URL=http://cobalt:9000/
    restart: unless-stopped

  api:
    build:
      context: .
      target: api
    environment:
      - COBALT_URL=http://cobalt:9000/
    depends_on:
      - cobalt
    restart: unless-stopped

  web:
    build:
      context: .
      target: web
    ports:
      - "8080:80" # Cambiado para no chocar con NPM
    depends_on:
      - api
    restart: unless-stopped