services:
  api:
    build:
      context: .
      target: api
    restart: unless-stopped

  web:
    build:
      context: .
      target: web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
