services:
  api:
    build:
      context: .
      target: api
    restart: unless-stopped

  web:
    build:
      context: .
      target: web
    ports:
      - "8080:80" # Cambiado para no chocar con NPM
    depends_on:
      - api
    restart: unless-stopped